return function (mappings)
  hs.fnutils.each(mappings, function (mapping)
    local windowFilter = hs.window.filter.new(mapping[1])
    local hotkey = hs.hotkey.new(mapping[2][1], mapping[2][2], function ()
      hs.eventtap.keyStroke(mapping[3][1], mapping[3][2], 0)
    end)
    windowFilter:subscribe(hs.window.filter.windowFocused, function()
      hotkey:enable()
    end)
    windowFilter:subscribe(hs.window.filter.windowUnfocused, function()
      hotkey:disable()
    end)
  end)
end
