export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/vendor/zsh/oh-my-zsh

DISABLE_AUTO_UPDATE=true
ZSH_CUSTOM=$DOTFILES/zsh/env/oh-my-zsh/custom

if [[ $(uname) == 'Darwin' ]]; then
    plugins+=("ansible-homebrew-custom")
    plugins+=("php-homebrew-custom")
    plugins+=("macos-custom")
fi

plugins=(
    brew
    composer-custom
    diff-so-fancy-custom
    docker-custom
    extract
    git
    git-custom
    laravel-sail-custom
    laravel5
    node-custom
    nvm-custom
    sublime
    vagrant-custom
    vi-mode
    z
    zsh-syntax-highlighting
    fzf-custom
)

PATH="/usr/local/sbin:$PATH"

for file in $DOTFILES/zsh/env/oh-my-zsh/includes/pre/*.zsh; do
    source "$file"
done

source $ZSH/oh-my-zsh.sh

for file in $DOTFILES/zsh/env/oh-my-zsh/includes/post/*.zsh; do
    source "$file"
done
