" vim:fdm=marker

" Local Vimrc {{{

if filereadable(expand("~/.local.vimrc.before"))
    source ~/.local.vimrc.before
endif

" }}}
" NeoBundle {{{

if has('vim_starting')
    set nocompatible
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
let vundle_readme=expand('~/.vim/bundle/neobundle.vim/README.md')
if !filereadable(vundle_readme)
    echo "Installing NeoBundle..."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

" packages
" ========
NeoBundle 'altercation/vim-colors-solarized'

call neobundle#end()
filetype plugin indent on
NeoBundleCheck

" }}}
" {{{ Temporary Settings

syntax on
inoremap jj <Esc>
set background=light
colorscheme solarized
set number
" }}}
