start_time="$(date +%s)"

# zshrc before
[[ -r ~/.zshrc.before ]] && . ~/.zshrc.before

# determine os
DOTFILES_OS=''
if [[ $(uname) == 'Linux' ]]; then
    DOTFILES_OS='LINUX'
elif [[ $(uname) == 'Darwin' ]]; then
    DOTFILES_OS='OSX'
fi

export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/.dotfiles
export DOTFILES_OS

ZSH_CUSTOM=$DOTFILES/zsh/oh-my-zsh/custom

plugins=(
    brew
    composer
    extract
    git
    grunt
    k
    laravel5
    sublime
    tmux
    tmuxinator
    vi-mode
    web-search
    z
    zshmarks
    zsh-syntax-highlighting
)

source $DOTFILES/zsh/oh-my-zsh/path.zsh
source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/oh-my-zsh/exports.zsh
source $DOTFILES/zsh/oh-my-zsh/aliases.zsh
source $DOTFILES/zsh/oh-my-zsh/functions.zsh

# zshrc after
[[ -r ~/.zshrc.after ]] && . ~/.zshrc.after

end_time="$(date +%s)"
echo .zshrc: $((end_time - start_time)) seconds
