start_time="$(date +%s)"

export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/.dotfiles

ZSH_CUSTOM=$DOTFILES/zsh/oh-my-zsh/custom

plugins=(
    brew
    composer
    extract
    git
    k
    laravel5
    pure
    sublime
    sudo
    tmux
    vi-mode
    web-search
    z
    zshmarks
    zsh-syntax-highlighting
)

source $DOTFILES/zsh/oh-my-zsh/path.zsh
source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/oh-my-zsh/exports.zsh
source $DOTFILES/zsh/oh-my-zsh/aliases.zsh
source $DOTFILES/zsh/oh-my-zsh/functions.zsh

# remove duplicates in path
typeset -U PATH

# load local zshrc
[[ -r ~/.local.zshrc ]] && . ~/.local.zshrc

end_time="$(date +%s)"
#echo .zshrc: $((end_time - start_time)) seconds
