export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/vendor/zsh/oh-my-zsh

DISABLE_AUTO_UPDATE=true
ZSH_CUSTOM=$DOTFILES/zsh/oh-my-zsh/custom

DOTFILES_PHP_VERSION=7.3

plugins=(
    brew
    composer
    extract
    git
    k
    laravel5
    sublime
    vi-mode
    yarn
    z
    #zsh-interactive-cd
    #zsh-nvm
    zsh-syntax-highlighting
    #zsh-autosuggestions
)

source $DOTFILES/zsh/oh-my-zsh/path.zsh
source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/oh-my-zsh/exports.zsh

if [[ $(uname) == 'Darwin' ]]; then
    source $DOTFILES/zsh/oh-my-zsh/aliases-macos.zsh
    source $DOTFILES/zsh/oh-my-zsh/functions-macos.zsh
fi

source $DOTFILES/zsh/oh-my-zsh/aliases.zsh
source $DOTFILES/zsh/oh-my-zsh/functions.zsh
source $DOTFILES/zsh/oh-my-zsh/fzf.zsh
source $DOTFILES/zsh/oh-my-zsh/toggle.zsh
source $DOTFILES/zsh/oh-my-zsh/direnv.zsh
#source $DOTFILES/zsh/oh-my-zsh/autosuggest.zsh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

# rvm
[ -s "$HOME/.rvm/scripts/rvm" ] && source "$HOME/.rvm/scripts/rvm"
