[character]
style_success = 'bold green'
style_error = 'bold red'

[directory]
style = "blue"

[git_branch]
symbol = ""
format="on [$symbol$branch]($style)"
style = "yellow"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold 196"

[nodejs]
style = "bold green"
format = "[JS $version]($style) "

[php]
format = "[PHP $version]($style) "

[username]
style_user = "purple bold"
