#!/bin/sh

open -a Seil
read -rsp $'Seil: Make sure Seil is running and press any key to continue...\n' -n1 key

echo "Seil: Initializing Settings"

CLI=/Applications/Seil.app/Contents/Library/bin/seil

$CLI set keycode_int8 76
$CLI set keycode_lang6 76
$CLI set keycode_ssapex_l4 111
$CLI set enable_capslock 1
$CLI set enable_jis_xfer 0
$CLI set enable_lang1 0
$CLI set enable_control_l 0
$CLI set enable_escape 0
$CLI set keycode_control_l 59
$CLI set keycode_again 111
$CLI set enable_int6 0
$CLI set keycode_int6 76
$CLI set enable_adb_keyboard_power 0
$CLI set keycode_select 111
$CLI set enable_command_l 0
$CLI set keycode_lang5 76
$CLI set enable_shift_l 0
$CLI set enable_undo 0
$CLI set enable_ssapex_upleft 0
$CLI set keycode_jis_nfer 102
$CLI set keycode_tab 48
$CLI set keycode_ssapex_upright 111
$CLI set enable_int2 0
$CLI set enable_option_l 0
$CLI set keycode_int4 76
$CLI set enable_lang8 0
$CLI set enable_jis_nfer 0
$CLI set keycode_paste 111
$CLI set keycode_lang4 76
$CLI set enable_cut 0
$CLI set keycode_command_r 54
$CLI set keycode_ssapex_l1 111
$CLI set enable_int9 0
$CLI set keycode_stop 111
$CLI set keycode_int2 76
$CLI set enable_lang6 0
$CLI set keycode_lang3 76
$CLI set enable_tab 0
$CLI set enable_int5 0
$CLI set enable_paste 0
$CLI set enable_enter 0
$CLI set enable_lang4 0
$CLI set enable_delete 0
$CLI set keycode_find 111
$CLI set keycode_lang2 76
$CLI set enable_execute 0
$CLI set keycode_enter 76
$CLI set enable_menu 0
$CLI set keycode_int9 76
$CLI set keycode_application 110
$CLI set enable_int1 0
$CLI set keycode_jis_kana 54
$CLI set keycode_escape 53
$CLI set enable_ssapex_upright 0
$CLI set enable_lang2 0
$CLI set enable_find 0
$CLI set keycode_space 49
$CLI set keycode_ssapex_l2 111
$CLI set keycode_ssapex_upleft 111
$CLI set keycode_shift_l 56
$CLI set keycode_lang1 76
$CLI set enable_jis_kana 0
$CLI set keycode_control_r 62
$CLI set keycode_int7 76
$CLI set enable_int8 0
$CLI set keycode_capslock 80
$CLI set enable_option_r 0
$CLI set enable_ssapex_l1 0
$CLI set enable_space 0
$CLI set enable_application 0
$CLI set enable_int4 0
$CLI set enable_return 0
$CLI set keycode_int5 76
$CLI set enable_lang9 0
$CLI set keycode_cut 111
$CLI set keycode_jis_xfer 104
$CLI set keycode_adb_keyboard_power 127
$CLI set keycode_lang9 76
$CLI set keycode_option_r 61
$CLI set keycode_execute 111
$CLI set enable_ssapex_l2 0
$CLI set keycode_int3 76
$CLI set enable_lang7 0
$CLI set keycode_ssapex_l3 111
$CLI set enable_copy 0
$CLI set keycode_command_l 55
$CLI set keycode_lang8 76
$CLI set enable_select 0
$CLI set enable_control_r 0
$CLI set keycode_undo 111
$CLI set enable_int7 0
$CLI set enable_shift_r 0
$CLI set keycode_int1 76
$CLI set enable_lang5 0
$CLI set enable_ssapex_l3 0
$CLI set enable_command_r 0
$CLI set enable_again 0
$CLI set keycode_delete 51
$CLI set keycode_lang7 76
$CLI set keycode_return 36
$CLI set enable_int3 0
$CLI set keycode_shift_r 60
$CLI set keycode_menu 111
$CLI set enable_lang3 0
$CLI set keycode_option_l 58
$CLI set enable_stop 0
$CLI set keycode_copy 111
$CLI set enable_ssapex_l4 0

echo "Seil: Done"
