# mcallan83/dotfiles
# bash aliases


# navigation 
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" 
alias --="cd -"

# shortcuts
alias h="history"
alias j="jobs"
alias v="vim"
alias ss="subl ."
alias oo="open ."

# misc 
alias cls="clear"
alias cc="clear"
alias qq="exit"

# ls 
if ls --color > /dev/null 2>&1; then 
	colorflag="--color" # gnu ls
else 
	colorflag="-G" # osx ls
fi
alias ll="ls -lF ${colorflag}" # long format
alias la="ls -laF ${colorflag}" #long format with hidden files
alias lsd='ls -lF ${colorflag} | grep "^d"' #only directories
alias ls="command ls ${colorflag}" #always use color for ls

# git
alias gg="gitsh"
alias gs="git status "

# web
alias gogh="open http://www.github.com"

# enable aliases to be sudo’ed
alias sudo='sudo '

# ip addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

# enhanced whois lookups
alias whois="whois -h whois-servers.net"

# url-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# source ~/.bashrc
alias reload='. ~/.bashrc'

# tree
if [ ! -x "$(which tree 2>/dev/null)" ]
then
  alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
fi

# edit vimrc
alias vimrc="vim ~/.vimrc"

# laravel php framework
alias art="php artisan"

# download file using curl
alias dl="curl -O "

# osx-specific
if [[ "$OSTYPE" =~ ^darwin ]]; then

	# copy public key to clipboard
	alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to clipboard.'"

	# merge pdf files
	# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
	alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

	# open file in quicklook
	alias ql='qlmanage -p 2>/dev/null'

	# trim new lines and copy to clipboard
	alias c="tr -d '\n' | pbcopy"

	# recursively delete `.DS_Store` files
	alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

	# show/hide hidden files in Finder
	alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
	alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

	# hide/show all desktop icons (useful when presenting)
	alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
	alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

	# copy external ip address to clipboard
	alias ipcopy="dig +short myip.opendns.com @resolver1.opendns.com | tr -d '\040\011\012\015' | pbcopy"

fi
