# mcallan83/dotfiles
# bashrc

#files
declare -a files=(
    $HOME/.rvm/scripts/rvm # load RVM *as a function*
    $HOME/.dotfiles/bash/bash_options # options
    $HOME/.dotfiles/bash/bash_exports # exports
    $HOME/.dotfiles/bash/bash_aliases # aliases
    $HOME/.dotfiles/bash/bash_functions # functions
    $HOME/.dotfiles/bash/scripts/* # scripts
    $HOME/.dotfiles/bash/bash_prompt # prompt
    $HOME/.localrc # local settings
    $HOME/.dotfiles/bash/bash_paths # paths (source after `.localrc` in case of custom paths)
)

# source readable files
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done
unset files

# bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi
